language: zh-Hans

theme: 
  switch: true 
  default: style-light 

favicon:
  logo: /img/favicon-32x32.png
  icon16: /img/favicon-32x32.png 
  icon32: /img/favicon-32x32.png
  appleTouchIcon: 
  webmanifest: 
  visibilitychange: false
  hidden: /failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！

assets:
  icons: 
    type: font 
    # 这里是您从 iconfont 处获得的图标链接。
    css: //at.alicdn.com/t/font_383361_cfn4m13f4v.css
    js:

user:
  name: Pokaman
  first_name: 苍狗
  last_name: 白云
  email: mm1314955811@163.com
  domain: https://mohalikeyou.github.io/
  avatar: /img/avatar.jpg
  describe: 个人博客
  ruleText: 暂不接受个人博客以外的友链申请。

top_bars:
  - title: home
    url: /
    children:
      - title: archives2
        url: /archives2/
  - title: archives
    url: /archives/
    noswup: true

sidebar:
  social:  # 社交地址
    - name: github
      icon: fab fa-github   
      url: https://github.com/mohalikeyou 
    - name: gitee
      icon: iconfont cg-gitee
      url: https://gitee.com/mohahaa
  typedTextPrefix: I`m
  typedText: [ 'A Technology Lover' ]
  info: # 个人信息 
    - key: 地址 
      val: 武汉       
    - key: 年龄
      val: 24 

banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
  archive:
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive

wordcount:
  enable: false
  count: true
  time: true

footer:
  copyrightYear: 2020
  powered:
    enable: true

  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00

is_toc: true

lazyload:
  enable: true

archive:
  type: more # less more

icons:
  # 主题切换图标
  sun: far fa-sun
  moon: far fa-moon
  # 首页视频播放
  play: fas fa-play
  # 邮箱
  email: far fa-envelope
  # 分类进入图标
  next: fas fa-arrow-right
  # 文章详情 日期
  calendar: far fa-calendar-alt
  # 文章详情 时间
  clock: far fa-clock
  # 文章详情 作者
  user: far fa-user
  # 返回顶部 v1.1.3+
  back_top: fas fa-arrow-up
  # 查询 v1.1.5+
  search: fas fa-search
  # 关闭 v1.1.5+
  close: fas fa-times
  # 打赏 v1.1.7+
  reward: fas fa-hand-holding-usd

search:
  enable: false
  type: engine #local engine
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: 